name: Deploy to Google Cloud Storage, Google CDN via Terraform.

on:
  push:
    branches:
      - main

env:
  GCS_BUCKET: ${{ github.event.repository.name }}
  TF_VAR_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_subdomain: ${{ secrets.SUBDOMAIN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create TF state bucket as necessary.
        run: |
          if ! gsutil ls -b gs://tf_state_$GCS_BUCKET > /dev/null 2>&1; then
            gsutil mb -p $TF_VAR_project_id -l us gs://tf_state_$GCS_BUCKET
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init -backend-config="bucket=tf_state_$GCS_BUCKET"
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

      - name: Upload to Cloud Storage
        run: gsutil -m rsync -r dist gs://${{ env.TF_VAR_subdomain }}.${{ env.TF_VAR_domain_name }}
